######################################################################
# Automatically generated by qmake (3.0) Wed Nov 23 11:33:21 2016
######################################################################

TEMPLATE = app
TARGET = ChessGame
INCLUDEPATH += .

QT += widgets
CONFIG += c++11

# Input
HEADERS += chessboard.h chesspiece.h
SOURCES += chessboard.cpp chesspiece.cpp main.cpp
RESOURCES += images.qrc
